---
session_name: dev
start_directory: ~/projects
windows:
  - window_name: dev
    layout: main-horizontal
    options:
      main-pane-height: 50
    panes:
      - focus: true
      - pane
      - pane
