{
  flake.modules.lib.mkConfig =
    { ... }:
    let
      hr =
        text:
        let
          parts = builtins.split "." text;
        in
        builtins.foldl' (text: part: if builtins.isList part then "${text}-" else text) "" (
          builtins.tail parts
        );
    in
    {
      mkConfig =
        {
          pkgs,
          shell ? "${pkgs.zsh}/bin/zsh",
          terminal ? "xterm-256color",
          plugins ? [ ],
        }:
        let
          is-package = pkgs.lib.types.package.check;
          get-plugin-name = plugin: if is-package plugin then plugin.pname else plugin.plugin.pname;

          base-config = ''
            set  -g default-terminal "xterm-256color"
          '';

          plugin-config = pkgs.lib.concatMapStringsSep "\n\n" (plugin: ''
            # ${get-plugin-name plugin}
            # ${hr (get-plugin-name plugin)}
            ${plugin.extraConfig or ""}
            run-shell ${if is-package plugin then plugin.rtp else plugin.plugin.rtp}
          '') plugins;
        in
        ''
          # This file is generated by https://github.com/dsnn/flakes

          # ========================== #
          #           BASE             #
          # ========================== #

          ${base-config}

          # ========================== #
          #           PLUGINS          #
          # ========================== #

          ${plugin-config}
        '';
    };
}
