{
  ...
}:
let
  tmuxConf = ''
    # This file is generated by https://github.com/dsnn/flakes/tmux

    #========================#
    #          BASE          #
    #========================#

    #========================#
    #         PLUGINS        #
    #========================#
  '';
in
{
  text.readme.parts.tmux =
    # markdown
    ''
      ## Tmux 

      [tmux](https://github.com/tmux/tmux/wiki) with configurations

    '';

  perSystem =
    { pkgs, ... }:
    {
      packages.tmux =
        let
          tmuxConfFile = pkgs.writeText "tmux.conf" tmuxConf;
        in
        pkgs.writeShellApplication {
          name = "tmux-wrapper";
          runtimeInputs = [ pkgs.tmux ];
          text = "tmux -f ${tmuxConfFile} \"$@\"";
        };
    };
}
